# **Beginner**



1. Python program to print all positive numbers in a range


*   Given start and end of a range, write a Python program to print all positive numbers in given range.



In [1]:
import time 
import numpy as np

In [9]:
start,end = -10,29
t_0 = time.time()
for i in range(start,end+1):
    if i > 0:
        print(i,end=" ")
t_1 = time.time()
print((t_1-t_0) * 100)

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 0.19996166229248047


In [8]:
t_0 = time.time()
arr = np.array(range(start,end+1))
print(arr[arr>0])
t_1 = time.time()
print((t_1-t_0)*100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
0.10006427764892578


2. Python | Remove empty tuples from a list
  



In [11]:
list_of_tuples = [(), ('ram','15','8'), (), ('laxman', 'sita'), 
          ('krishna', 'akbar', '45'), ('',''),()]

In [20]:
final_list = [t for t in list_of_tuples if len(t) != 0]
final_list

[('ram', '15', '8'), ('laxman', 'sita'), ('krishna', 'akbar', '45'), ('', '')]

3. How to count unique values inside a list using counter

In [22]:
from collections import Counter

In [23]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8]


In [26]:
items = Counter(input_list).keys()
print(len(items))

5


In [27]:
#using sets
print(len(set(input_list)))

5


4. Extract elements with Frequency greater than K




In [30]:
test_list = [4, 6, 4, 3, 3, 4, 3, 7, 8, 8]
k = 2
for i,j in Counter(test_list).items():
    if j > k :
        print(i)

4
3


5. Retain records with N occurrences of K

*   Sometimes, while working with Python tuples list, we can have a problem in which we need to perform retention of all the records where occurrences of K is N times.





In [31]:
test_list = [(4, 5, 6, 4, 4), (4, 4, 3), (4, 4, 4), (3, 4, 9)]

In [32]:
k,n=4,3

In [33]:
res = [i for i in test_list if i.count(k)==n]
res

[(4, 5, 6, 4, 4), (4, 4, 4)]

6. Ways to remove multiple empty spaces from string List


In [34]:
test_list = ['gfg', '   ', ' ', 'is', '            ', 'best']

In [40]:
res = [i for i in test_list if i.strip()]
res

['gfg', 'is', 'best']

7. How to create a dictionary where a key is formed using inputs?

In [1]:
n = int(input())

 5


In [3]:
d = {}
for i in range(0,n):
        word = input().split()
        d[word[0]]=word[1]


 12 hi
 34 ko
 12 op
 42 ik
 10 lp


In [4]:
d

{'12': 'op', '34': 'ko', '42': 'ik', '10': 'lp'}

8. Create Nested Dictionary using given List

In [5]:
test_dict = {'Gfg' : 4, 'is' : 5, 'best' : 9} 
test_list = [8, 3, 2]

In [7]:
test_dict.items()

dict_items([('Gfg', 4), ('is', 5), ('best', 9)])

In [8]:
d = {i:j for i,j in zip(test_list,test_dict.items()) }

In [9]:
d

{8: ('Gfg', 4), 3: ('is', 5), 2: ('best', 9)}

9. Print anagrams together in Python using List and Dictionary

10. Dictionary with maximum count of pairs

In [10]:
test_list = [{"gfg": 2, "best" : 4}, 
             {"gfg": 2, "is" : 3, "best" : 4}, 
             {"gfg": 2}]

In [12]:
print(max(test_list, key = len))

{'gfg': 2, 'is': 3, 'best': 4}


In [18]:
#Another method
d = {len(i):i for i in test_list}
d[max(d)]

{'gfg': 2, 'is': 3, 'best': 4}

11. Convert Nested dictionary to Mapped Tuple

In [20]:
from collections import defaultdict    

In [21]:
test_dict = {'gfg' : {'x' : 5, 'y' : 6}, 'is' : {'x' : 1, 'y' : 4}, 
                                      'best' : {'x' : 8, 'y' : 3}}

In [23]:
defaultdict(tuple)

defaultdict(tuple, {})

In [34]:
x,y = [],[]
for i,j in test_dict.items():
    x.append(j['x'])
    y.append(j['y'])
tup = (('x',tuple(x)),('y',tuple(y)))

In [35]:
tup

(('x', (5, 1, 8)), ('y', (6, 4, 3)))

In [42]:
#Another method
res = defaultdict(tuple)
for key, val in test_dict.items():
    for ele in val:
        res[ele] += (val[ele], )

In [43]:
tuple(res.items())

(('x', (5, 1, 8)), ('y', (6, 4, 3)))

12. Convert Matrix to dictionary

In [44]:
test_list = [[5, 6, 7], [8, 3, 2], [8, 2, 1]] 

In [45]:
d = {i+1:test_list[i] for i in range(len(test_list))}

In [46]:
d

{1: [5, 6, 7], 2: [8, 3, 2], 3: [8, 2, 1]}

13. Extract Unique values dictionary values

In [47]:
test_dict = {'gfg' : [5, 6, 7, 8],
             'is' : [10, 11, 7, 5],
             'best' : [6, 12, 10, 8],
             'for' : [1, 2, 5]}

In [60]:
list({ele for val in test_dict.values() for ele in val})

[1, 2, 5, 6, 7, 8, 10, 11, 12]

14. Write a Python function to find the Max of three numbers. 

In [61]:
def max_2(a,b):
    if a<b:
        return b
    else:
        return a

In [62]:
def max_3(a,b,c):
    return max_2(a,max_2(b,c))

In [63]:
max_3(2,-1,10)

10

15. Find the most frequent value in a NumPy array

In [68]:
x = np.array([1,2,3,4,5,10,2,1,1,1])

In [71]:
np.bincount(x).argmax()

1

16. How to check whether specified values are present in NumPy array?

In [72]:
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])

In [73]:
10 in n_array

False

17. How to build an array of all combinations of two NumPy arrays?

In [74]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])

In [78]:
np.array(np.meshgrid(array_1,array_2)).T.reshape(-1,2)

array([[1, 4],
       [1, 6],
       [2, 4],
       [2, 6]])

18. numpy.swapaxes() function | Python

In [79]:
arr = np.array([[2, 4, 6]])

In [80]:
np.swapaxes(arr,0,1)

array([[2],
       [4],
       [6]])

19. In this example we can see that by using np.eigvals() method, we are able to get the eigen values of a matrix by using this method.



In [83]:
np.linalg.eigvals([array_1,array_2])

array([-0.27491722,  7.27491722])

20. How to inverse a matrix using NumPy

In [84]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [85]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

21. How to count the frequency of unique values in NumPy array?

In [86]:
ini_array = np.array([10, 20, 5,
                      10, 8, 20,
                      8, 9])

In [89]:
unique,counts = np.unique(ini_array,return_counts=True)

In [90]:
unique

array([ 5,  8,  9, 10, 20])

In [91]:
counts

array([1, 2, 1, 2, 2], dtype=int64)

22. Compute the outer product of two given vectors using NumPy in Python

In [92]:
np.outer(array_1,array_2)

array([[ 4,  6],
       [ 8, 12]])

23. Compute the covariance matrix of two given NumPy arrays

In [93]:
array1 = np.array([2, 1, 1, 4])
array2 = np.array([2, 2, 1, 1])

In [94]:
np.cov(array1,array2)

array([[ 2.        , -0.33333333],
       [-0.33333333,  0.33333333]])

24. Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [2]:
a = np.array([2, 6])
b = np.array([3, 10])

In [3]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

In [26]:
def vec_products(m,n):
    print(f"{np.inner(m,n)} \n")
    print(f"{np.outer(m,n)} \n")
    print(f"{np.cross(m,n)} \n")

In [27]:
vec_products(a,b)

66 

[[ 6 20]
 [18 60]] 

2 



In [28]:
vec_products(x,y)

[[17 52]
 [13 62]] 

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] 

[[-20   4   7]
 [-84  36  20]] 



25. Replace NumPy array elements that doesn’t satisfy the given condition

In [30]:
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
num = 50.0

In [31]:
n_arr[n_arr>num] = 15.5

In [32]:
n_arr

array([15.5       , 42.48558583, 15.5       ])

26. Replace NaN values with average of columns

In [42]:
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

In [43]:
col_mean = np.nanmean(ini_array, axis = 0)
col_mean

array([2. , 3. , 4.5, 6. ])

In [44]:
inds = np.where(np.isnan(ini_array))
inds

(array([0, 1], dtype=int64), array([3, 2], dtype=int64))

In [47]:
ini_array[inds] = np.take(col_mean, inds[1])
ini_array

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

27. Replace negative value with zero in numpy array

In [48]:
ini_array1 = np.array([1, 2, -3, 4, -5, -6])
ini_array1

array([ 1,  2, -3,  4, -5, -6])

In [49]:
ini_array1[ini_array1<0] = 0

In [50]:
ini_array1

array([1, 2, 0, 4, 0, 0])

29. Python | numpy.fill_diagonal() method

In [52]:
array = np.zeros((3, 3),int)
np.fill_diagonal(array,1)
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])